import { Card } from "@/components/ui/Card";
import { getCurrentBusiness } from "@/lib/business/current";
import { getBusinessSubscription } from "@/features/billing/subscription";
import { BILLING_PLANS } from "@/features/billing/config";
import { PlanChangeButton, CancelSubscriptionButton } from "@/components/billing/PlanActions";

export const dynamic = "force-dynamic";

export default async function BillingPage() {
  const { business, supabase } = await getCurrentBusiness();
  if (!business) return <Card className="p-6"><h1 className="text-xl font-bold">Billing</h1><p className="mt-2 text-sm text-[#52636B]">Create your business workspace first.</p></Card>;
  const { subscription, plan, planId } = await getBusinessSubscription(supabase, business.id);
  const { count } = await supabase.from("invoices").select("id", { count: "exact", head: true }).eq("business_id", business.id).in("status", ["draft", "scheduled", "due", "overdue"]);
  const used = count ?? 0;
  return <div><p className="text-sm font-bold uppercase tracking-[.14em] text-[#087F78]">Billing</p><h1 className="mt-2 text-3xl font-bold">Plan & subscription</h1><p className="mt-2 max-w-2xl text-[#52636B]">Manage your workspace plan and see the invoice capacity available to you.</p>
    <div className="mt-8 grid gap-5 lg:grid-cols-3"><Card className="p-6 lg:col-span-2"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm text-[#52636B]">Current plan</p><h2 className="mt-1 text-2xl font-bold">{plan.name}</h2><p className="mt-1 text-sm text-[#52636B]">{plan.priceCents === 0 ? "Free" : `$${(plan.priceCents/100).toFixed(0)}/month`} · {subscription?.status ?? "active"}</p></div><span className="rounded-full bg-[#E8F7F4] px-3 py-1 text-xs font-semibold text-[#087F78]">{planId}</span></div><div className="mt-7"><div className="flex justify-between text-sm"><span>Active invoices</span><span className="font-semibold">{used} / {plan.invoiceLimit}</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-[#E8F7F4]"><div className="h-full rounded-full bg-[#16B8A6]" style={{ width: `${Math.min(100, used / plan.invoiceLimit * 100)}%` }} /></div></div>{subscription?.current_period_end && <p className="mt-5 text-sm text-[#52636B]">Current period ends {new Date(subscription.current_period_end).toLocaleDateString()}.</p>}{subscription?.cancel_at_period_end && <p className="mt-3 text-sm font-semibold text-[#087F78]">Cancellation is scheduled for the end of this billing period.</p>}</Card><Card className="p-6"><h2 className="font-bold">Billing status</h2><p className="mt-2 text-sm text-[#52636B]">Provider: {subscription?.provider ?? "Not connected"}</p><p className="mt-1 text-sm text-[#52636B]">Customer billing is separate from your clients’ invoice payment links.</p></Card></div>
    <section className="mt-8"><h2 className="text-xl font-bold">Plans</h2><div className="mt-4 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{Object.values(BILLING_PLANS).map(p=><Card key={p.id} className={`flex flex-col p-5 ${p.id===planId ? "ring-2 ring-[#16B8A6]" : ""}`}><div className="flex-1"><p className="text-lg font-bold">{p.name}</p><p className="mt-1 text-2xl font-bold">{p.priceCents === 0 ? "$0" : `$${p.priceCents/100}`}<span className="text-xs font-normal text-[#52636B]">{p.priceCents ? "/month" : " forever"}</span></p><p className="mt-2 text-sm text-[#52636B]">Up to {p.invoiceLimit} active invoices.</p><ul className="mt-4 space-y-2 text-sm text-[#52636B]"><li>✓ Automatic email reminders</li><li>{p.customSchedules ? "✓" : "—"} Custom schedules</li><li>{p.analytics ? "✓" : "—"} Analytics</li><li>{p.teamMembers > 1 ? `✓ Up to ${p.teamMembers} team members` : "— Single user"}</li><li>{p.clientPortal ? "✓" : "—"} Client portal</li><li>{p.customTemplates ? "✓" : "—"} Custom email templates</li></ul></div><div className="mt-5">{p.id === planId ? <span className="text-sm font-semibold text-[#087F78]">Current plan</span> : p.id === "free" ? <span className="text-xs text-[#52636B]">Free fallback plan</span> : <PlanChangeButton businessId={business.id} plan={p.id} />}</div></Card>)}</div></section>
    {planId !== "free" && <Card className="mt-8 p-6"><h2 className="font-bold">Cancellation</h2><p className="mt-2 text-sm text-[#52636B]">Cancellation is designed to take effect at the end of the current period so existing data is not destroyed.</p><div className="mt-4"><CancelSubscriptionButton businessId={business.id} /></div></Card>}
  </div>;
}
